config/routes.rb
Rails.application.routes.draw do
  resources :visits
  resources :sites
  resources :neighborhoods   
  resources :users
  resources :cities

  get '/neighborhoods/:id/ny_neighborhoods', to: 'neighborhoods#ny_neighborhoods', as: :ny_neighborhoods
  get '/neighborhoods/:id/chi_neighborhoods', to: 'neighborhoods#chi_neighborhoods', as: :chi_neighborhoods

  delete '/users/:id/destroy', to: 'users#destroy', as: 'delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :neighborhoods
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  belongs_to :city
  has_many :sites
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :neighborhood
  has_many :visits
  has_many :users, through: :visits
end

app/models/user.rb
class User < ApplicationRecord
    has_many :visits
    has_many :sites, through: :visits
    validates :name, presence: true, uniqueness: true
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :site
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    def index
        @cities = City.all
    end

    def show
        @city = City.find(params[:id])
    end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
    def index
        @neighborhoods = Neighborhood.all
    end

    def show
        @neighborhood = Neighborhood.find(params[:id])
    end

    def ny_neighborhoods
        @ny_neighborhoods = Neighborhood.where(city_id: 1)
    end

    def chi_neighborhoods
        @chi_neighborhoods = Neighborhood.where(city_id: 2)
    end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
    
    def index
        @sites = Site.all
    end

    def show
        @site = Site.find(params[:id])
    end

    def manhattan
    end

    def brooklyn
    end

    def queens
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @cities = City.all
        @neighborhoods = Neighborhood.all
    end

    def new 
        @user = User.new
    end

    def create
        @new_user = User.create(user_params)
        if @new_user.valid? 
            redirect_to user_path(@new_user)
        else
            flash[:error]= @new_user.errors.full_messages
            redirect_to new_user_path(@new_user)
        end
    end

    def update
        @city = City.find(params[:id])
        byebug
        redirect_to neighborhoods_path
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to new_user_path
    end

private
    def user_params
        params.require(:user).permit(:name)
    end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

    def show
        @visit = Visit.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sightseeing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/neighborhoods/chi_neighborhoods.erb
<h1> Chicago Neighborhoods </h1>
<br>
    <% @chi_neighborhoods.each do |n| %>
        <%= link_to n.name %> <br>
        <% end %>

app/views/neighborhoods/index.erb
<h1> Neighborhoods </h1>
<br>
<% @neighborhoods.each do |n| %>
    <%= n.name %> <br>
    <% end %>

app/views/neighborhoods/ny_neighborhoods.erb
<h1> New York Neighborhoods </h1>
<br>
    <% @ny_neighborhoods.each do |n| %>
        <%= link_to n.name %> <br>
        <% end %>

app/views/sites/index.erb
<h1>These are all of the sites.</h1>

<% @sites.each do |site|%>
    <%= site.site_name %><br>
    <% end %>

app/views/sites/show.erb
<h1> <%= @site.site_name %> </h1>

    <p> <%= @site.description %> </p>

app/views/users/new.erb
<h1> Create a new user </h1>

<%= form_for @user do |u| %>
    <%= u.label :name %>
    <%= u.text_field :name %>
    <%= u.submit "Create Profile" %>
<% end %>

<br>

<% if flash[:error] %>
    <% flash[:error].each do |e| %>
        <%= e %>
    <% end %>
<% end %>

app/views/users/show.erb
<h1> <%= @user.name %> </h1>

<%= link_to "New York", ny_neighborhoods_path %> <br>
<%= link_to "Chicago", chi_neighborhoods_path %> <br><br>

<%= button_to "Delete User", delete_path(@user), method: :delete %>